### ISSUE TITLE
several unsafe usages in this crate are unsound

### ISSUE THREAD

**Issue by ethanpailes** [algesten/hoot#2]
The unsafe usages in this crate are unsound or uncomfortably close, though they likely won't be an issue in practice. There are two types of unsafe usage: transmute to transition type states and transmute to make a transparent wrapper newtype.

The more common is the transmute to transition type states. This is possibly unsound since repr(Rust) generic types with different generic parameters are not explicitly guaranteed to have the same layout, even if the parameter types do. It is also pretty trivial to get rid of this usage of unsafe since you can just destructure and reconstruct the types (which could get unwieldy if the types in question were large, but fortunately they are not).

The second type of unsafe usage only happens once. The `transmute_headers` routine in `header.rs` relies on httparse::Header and hoot::Header having the same representation, but though they are declared with the same fields, this is not guaranteed. Fortunately, rust has [`#[repr(transmute)]`](https://doc.rust-lang.org/nomicon/other-reprs.html#reprtransparent) which is meant for just this situation. The fields of hoot::Header are private and wrapped in nice getters, so the fix does not even require a semver bump.

I uploaded a [patch](https://github.com/ethanpailes/hoot/commit/a68f1dd4410cf951da23f2722700f087ceec7597) that should address these problems to my fork, and I'm about to open a PR with the changes.

**Comment by algesten** [comment]
@ethanpailes Thanks for this!

The destructuring is simple for this project, but I'm sure I seen the type state transmute in other places. Would there be any circumstance this is valid?

Thanks,
Martin

**Comment by algesten** [comment]
Maybe by using `#[repr(C)]`?

**Comment by algesten** [comment]
Released as 0.1.4 with hootbin 0.1.4 as well.

**Comment by ethanpailes** [comment]
Wow, super fast turnaround on this, thanks!

> The destructuring is simple for this project, but I'm sure I seen the type state transmute in other places. Would there be any circumstance this is valid?

I'm honestly not sure. `#[repr(C)]` does seem more likely to be sounds since there is an actually defined memory layout, but since C itself does not have generics, I would still be a little worried. I have to confess I opened this issue as the result of the unsafe review we do when importing a third party crate at google, so I was mostly relaying what the actual unsafe expert told me.

 In any case, just destructuring and re-building removes the worry. For more deeply nested types there might be a pattern where you hang the transition() method off the Typ wrapper for your typestates and then use that to avoid having to totally destructure and rebuild the type, though I would have to play around with it, seems like you might still need to destructure and rebuild the type.

**Comment by algesten** [comment]
Cool. Also if you upgrade to ureq 2.9.6 (which is where I assume you encountered it), this dependency becomes optional, so less of a worry for unsafe review.
